### ISSUE TITLE
Consulta: poncho CIAA-EDU para la enseñanza de programación de microcontroladores

### ISSUE THREAD

**Issue by fcladera** [ciaa/Ponchos#1]
Hola a todos,

Antes que nada, disculpas si este no es el lugar correcto para publicar
este mensaje. He solicitado adhesión al grupo EDUCIAA en google groups,
pero todavía no tengo respuesta.

Mi nombre es Fernando Cladera. Soy ingeniero en Mecatrónica, y
actualmente estoy participando como adscripto en la cátedra de
Microcontroladores y Electrónica de Potencia de la carrera de Ing.
Mecatrónica,  Facultad de Ingeniería, UNCuyo.

Nos gustaría dentro de la cátedra migrar de Microchip a la EDU-CIAA-NXP.
La plataforma presenta varias ventajas desde el punto de vista de la
enseñanza, por ejemplo el debug en tiempo de ejecución utilizando
OpenOCD, el hecho de que sea ARM, el desarrollo de un RTOS específico
para la plataforma, entre otros. La idea es utilizar la placa "bare
metal" en un principio, para que los alumnos aprendan a escribir
drivers, utilizar periféricos y entender los principios de
funcionamiento de un microcontrolador.

Como parte del proyecto, creo que sería una buena idea contar con una
placa similar a un "Developer's Kit" [1](http://www.embeddedartists.com/products/kits/lpc2468_kit.php), para montar la EDU-CIAA. Había
pensado agregar los siguientes componentes:
- Potenciómetros
- Integrados que implementen comunicación SPI e I2C (memorias, o
  sensores de temperatura/presión como LM75)
- Interfaz RS232 con MAX232
- Conector de red
- Salida de potencia con MOSFET
- Display LCD o 7 segmentos
- ULN20003 para manejar pequeños motores CC o PaP
- ...?

Había pensado utilizar componentes convencionales (through-hole) para
facilitar la adquisición de componentes y el montaje en la placa (para
que pueda ser realizado por los alumnos). Además, espero desarrollar una
placa clase 2 o 3, para que sea más sencillo fabricarla.

¿Es interesante una contribución de este tipo? ¿Qué otro componente
consideran que podría ser útil?

He visto que hay un problema de licencia con el poncho "Interfaz de
Usuario". Espero que este desarrollo tenga las licencias adecuadas para
poder agregarlo al repositorio de ponchos.

Saludos,

Fernando Cladera
(fcladera [at] fcladera.com)

**Comment by pridolfi** [comment]
Me parece buena idea. Lo que sí yo intentaría mantener el formato de poncho, sin extenderme demasiado en las dimensiones del PCB. Si querés andá armándolo en KiCad y te damos una mano para revisarlo.
Saludos!

**Comment by fcladera** [comment]
Gracias Pablo por la rápida respuesta.

Seguimos la discusión por el grupo para evitar duplicados.

https://groups.google.com/forum/#!topic/embebidos32/JN9B8jVXWPc
